use async_trait::async_trait;
use easy_macros::macros::always_context;

struct DatabaseSetupTest {
    t: ExampleTable,
}

struct ExampleTable {
    id: i64,
    field0: String,
    field1: String,
    field2: i32,
    field3: i64,
    field4: i16,
}
#[always_context]
#[async_trait]
impl crate::DatabaseSetup for ExampleTable {
    async fn setup(
        conn: &mut (impl crate::EasyExecutor + Send + Sync),
        used_table_names: &mut Vec<String>,
    ) -> anyhow::Result<()> {
        use crate::EasyExecutor;

        //If table doesn't exist ( https://stackoverflow.com/questions/1601151/how-do-i-check-in-sqlite-whether-a-table-exists )
        //Save current version to easy_sql_tables table

        //Create Unique id for every table (saved inside of macro file before compilation)
        //Every Unique id is generated by the build.rs
        //Check for table removal inside of build script

        //Create migrations based on table number change
        //Check if default value was provided by user (if field is not Option<>)

        //TODO In procedural macro
        // save table fields into a file (when the version number attribute changed)

        //In sqlite you can only add new columns and rename old ones
        //(without recreating a table https://www.sqlitetutorial.net/sqlite-alter-table/ )

        Ok(())
    }
}
