//! Tests used to stabilise code that is or will be generated by procedural macros.
mod insert;
mod output;
mod query;
mod query_lazy;
mod sql;
mod table;
mod update;

use super::*;

//TODO Test whenever query_lazy!(...).fetch(conn) borrows conn forever (it shouldn't)
