use std::collections::HashMap;

mod sql_type;

pub struct TableDataVersion {
    pub table_name: String,
    pub fields: Vec<(String, sql_type::SqlType)>,
}

pub struct TableData {
    pub saved_versions: HashMap<u64, TableDataVersion>,
    pub latest_version: u64,
}

pub struct CompilationData {
    ///Key - table id, generated by build macro, put in #[sql(unique_id = "...")] attribute on struct
    pub tables: HashMap<String, TableData>,
}

impl CompilationData {
    pub fn is_duplicate_table_name(
        &self,
        current_unique_id: &str,
        table_name: &str,
    ) -> anyhow::Result<bool> {
        for (unique_id, table_data) in self.tables.iter() {
            if unique_id == current_unique_id {
                continue;
            }
            let latest_version_data = table_data.saved_versions.get(k);
        }
    }
}

//TODO Check for table removal inside of build script

//In sqlite you can only add new columns and rename old ones
//(without recreating a table https://www.sqlitetutorial.net/sqlite-alter-table/ )
