//! Tests used to stabilise code that is or will be generated by procedural macros.
mod insert;
mod output;
mod query;
mod query_lazy;
mod table;
mod update;

use super::*;

//TODO Test whenever query_lazy!(...).fetch(conn) borrows conn forever (it shouldn't)

/// Represents a connection that will be never created
/// TODO will be changed conditionally when the `watcher` feature will be added
#[allow(dead_code)]
type NeverConnection = crate::Connection<TestDriver>;
